name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build all platforms
      run: npm run build
      
    - name: Create release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.dmg
          dist/*.exe
          dist/*.AppImage
          dist/*.deb
          dist/*.rpm
          dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}